name: CI

on:
  push:
    branches: [ "main" ]
    tags:     'v*'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:
  pull_request:

jobs:

  linux:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install -y libavcodec-dev libavformat-dev libavutil-dev libswscale-dev

    - name: build
      run: source compile.sh

    - name: test
      run: ./caffeine

    - name: test video upload
      uses: actions/upload-artifact@v4
      with:
        name: out.mp4
        path: out.mp4
